[package]
name = "polimorphic"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/1_lib.rs"
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
rand = "0.8"
proc-macro2 = "1.0"
num-bigint = "0.4"
